### ISSUE TITLE
Create a database structure for the Screenings-database

### ISSUE THREAD

**Issue by Weeezzt** [Kookiie88/B7_Inlamning_4a#2]
Make a structure that we will use when we are connecting  each movie for the correct screenings on the correct date

**Comment by Kookiie88** [comment]
The screening database structure organizes information about each screening, capturing details such as the date, start time, and associated movie ID.

### Screenings collection

This collection will store all the screenings of the movies.

| Field     | Type   | Description                                                       |
| --------- | ------ | ----------------------------------------------------------------- |
| id        | Number | The id of the screening                                           |
| movieID   | Number | The id of the movie that this screening belongs to                |
| date      | String | The date of the screening                                         |
| startTime | String | The start time of the screening                                   |
| seats     | Array  | An array of objects with the seatNumber and handicap of each seat |
