### ISSUE TITLE
Create a structure for the Users-database

### ISSUE THREAD

**Issue by Weeezzt** [Kookiie88/B7_Inlamning_4a#4]

**Comment by Kookiie88** [comment]
The user database securely stores essential user details, including names, phone numbers, emails, and passwords. It also tracks user privileges, distinguishing between admin and regular users, and records whether users have any handicaps or accessibility needs.

### Users collection

This collection will store all the users that can access the application.

| Field       | Type    | Description                                   |
| ----------- | ------- | --------------------------------------------- |
| id          | Number  | The id of the user                            |
| name        | String  | The name of the user                          |
| email       | String  | The email of the user                         |
| password    | String  | The password of the user                      |
| phoneNumber | String  | The phone number of the user                  |
| admin       | Boolean | Whether the user is an admin or not           |
| handicap    | Boolean | Whether the user needs a handicap seat or not |
